# Challenge your Logical  Pandas Python

101 questions to help you improve your analysis skills with jupyter.


1. How to import pandas and check the version?


In [2]:
import pandas as pd

In [3]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Serbian (Latin)_Serbia.1252

pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli 

2. How to create a series from a list, numpy array and dict?


In [4]:
mylist = list('abcedfghijklmnopqrstuvwxyz')

In [5]:
print(mylist)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [6]:
ser = pd.Series(mylist)

In [7]:
print(ser)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [9]:
import numpy as np

In [10]:
myarr = np.arange(26)
print(myarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]


In [11]:
ser = pd.Series(myarr)

In [12]:
print(ser)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32


In [13]:
mydict = dict(zip(mylist, myarr))

In [14]:
print(mydict)

{'a': 0, 'b': 1, 'c': 2, 'e': 3, 'd': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [15]:
ser = pd.Series(mydict)
print(ser)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32


3. How to convert the index of a series into a column of a dataframe?

In [16]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [17]:
mylist = list('abcedfghijklmnopqrstuvwxyz')

In [18]:
ser = pd.Series(mylist)
ser.to_frame()
print(ser)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [19]:
df = ser.to_frame().reset_index()
print(df.head())

   index  0
0      0  a
1      1  b
2      2  c
3      3  e
4      4  d


4. How to combine many series to form a dataframe?


In [20]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [21]:
df=pd.concat([ser1,ser2],axis=1)
print(df)


    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25


In [22]:
print(df.head())


   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


How to assign name to the series’ index?

In [23]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [25]:
ser.rename("alphabets")

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: alphabets, dtype: object

6. How to get the items of series A not present in series B?


From ser1 remove items present in ser2.

In [27]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [28]:
res = ser1[~ser1.isin(ser2)]
print(res)

0    1
1    2
2    3
dtype: int64


7. How to get the items not common to both series A and series B?

Get all items of ser1 and ser2 not common to both

In [29]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [30]:
union = pd.Series(np.union1d(ser1, ser2)) #combine to series

In [31]:
intersect = pd.Series(np.intersect1d(ser1, ser2))# intersection of the series

In [33]:
notcommonseries = union[~union.isin(intersect)] # uncommon elements in both the series 
print(notcommonseries)

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [34]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [35]:
print(ser)

0     15.688437
1      4.806242
2     12.622296
3      8.522431
4     15.150375
5      5.321725
6     18.881260
7      9.664941
8      8.841973
9      9.087968
10    12.544047
11     2.764899
12    10.506380
13     3.526115
14    10.918010
15    12.505226
16    21.839864
17    -5.410442
18    17.295279
19    11.904612
20    13.036135
21    15.988686
22     4.746463
23    15.207253
24     7.164257
dtype: float64


In [36]:
result = np.percentile(ser, q=[0, 25, 50, 75, 100])
print(result)

[-5.4104419   7.1642571  10.9180104  15.15037529 21.83986399]


9. How to get frequency counts of unique items of a series?
Calculte the frequency counts of each unique value ser.

In [39]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser)

0     d
1     c
2     f
3     d
4     g
5     e
6     d
7     a
8     a
9     e
10    e
11    e
12    f
13    h
14    b
15    b
16    d
17    f
18    d
19    e
20    b
21    d
22    h
23    e
24    d
25    d
26    h
27    g
28    c
29    f
dtype: object


In [40]:
ser.value_counts()

d    8
e    6
f    4
h    3
b    3
c    2
g    2
a    2
dtype: int64

10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

In [41]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))


In [45]:
result = ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
print(ser)

0     Other
1     Other
2         2
3     Other
4         2
5         2
6         2
7     Other
8         2
9     Other
10    Other
11    Other
dtype: object


11. How to bin a numeric series to 10 groups of equal size?
Bin the series ser into 10 equal deciles and replace the values with the bin name.


In [47]:
ser = pd.Series(np.random.random(20))

In [48]:
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0     8th
1     4th
2     2nd
3    10th
4     8th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

12. How to convert a numpy array to a dataframe of given shape? (L1)
Reshape the series ser into a dataframe with 7 rows and 5 columns



In [50]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [52]:
arr = ser.values #counvort into arr

In [53]:
reshaped_arr = arr.reshape((7, 5))

In [54]:
print(reshaped_arr)

[[9 1 2 4 5]
 [7 9 7 1 2]
 [3 4 1 7 7]
 [9 2 1 8 3]
 [5 8 2 9 1]
 [5 2 5 4 7]
 [7 6 3 3 7]]


In [55]:
df = pd.DataFrame(ser.values.reshape(7,5)) #into DataFrame

In [56]:
print(df)

   0  1  2  3  4
0  9  1  2  4  5
1  7  9  7  1  2
2  3  4  1  7  7
3  9  2  1  8  3
4  5  8  2  9  1
5  5  2  5  4  7
6  7  6  3  3  7


13. How to find the positions of numbers that are multiples of 3 from a series?
Find the positions of numbers that are multiples of 3 from ser.

In [70]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [71]:
result = np.where(ser % 3==0)

In [72]:
print(result)

(array([6], dtype=int64),)


14. How to extract items at given positions from a series?
From ser, extract the items at positions in list pos.

In [74]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [75]:
result = ser.take(pos)

In [76]:
print(result)

0     a
4     e
8     i
14    o
20    u
dtype: object


15. How to stack two series vertically and horizontally ?
Stack ser1 and ser2 vertically and horizontally (to form a dataframe).



In [80]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [78]:
df = pd.concat([ser1, ser2], axis = 1)#Horizontally 

In [79]:
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [81]:
df = pd.concat([ser1, ser2], axis = 0)#Vertically 


In [82]:
print(df)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


16. How to get the positions of items of series A in another series B?
Get the positions of items of ser2 in ser1 as a list.

In [84]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [85]:
result = [pd.Index(ser1).get_loc(i) for i in ser2]

In [87]:
print(result)

[5, 4, 0, 8]


17. How to compute the mean squared error on a truth and predicted series?
Compute the mean squared error of truth and pred series.

In [88]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [89]:
MSE = np.square(np.subtract(truth,pred)).mean()

In [90]:
print(MSE)

0.2656014623004312


18. How to convert the first character of each element in a series to uppercase?
Change the first character of each word to upper case in each word of ser.

In [92]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [93]:
ser = ser.str.capitalize()

In [94]:
print(ser)

0     How
1      To
2    Kick
3    Ass?
dtype: object


19. How to calculate the number of characters in each word in a series?

In [95]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])


In [96]:
rst = ser.map(lambda calc: len(calc))

In [97]:
print(rst)

0    3
1    2
2    4
3    4
dtype: int64


20. How to compute difference of differences between consequtive numbers of a series?
Difference of differences between the consequtive numbers of ser.



In [98]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])


In [99]:
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [100]:
21. How to convert a series of date-strings to a timeseries?


Object `timeseries` not found.


In [102]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

22. How to get the day of month, week number, day of year and day of week from a series of date strings?
Get the day of month, week number, day of year and day of week from ser.

In [115]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
from dateutil.parser import parse


In [116]:
ser_ts = ser.map(lambda x: parse(x))


In [120]:
print("Date: ", ser_ts.dt.day.tolist())
print("Week number: ", ser_ts.dt.weekofyear.tolist())


Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]


C:\Users\Davor\AppData\Local\Temp\ipykernel_17648\1460111136.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print("Week number: ", ser_ts.dt.weekofyear.tolist())
